FROM python:3.12-slim

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends git build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-api.txt requirements-training.txt requirements-mlflow.txt ./
RUN pip install --no-cache-dir -r requirements-api.txt \
    && pip install --no-cache-dir -r requirements-training.txt \
    && pip install --no-cache-dir -r requirements-mlflow.txt

COPY app app
COPY scripts scripts
COPY src src
COPY dvc.yaml params.yaml ./
COPY models/registry.json models/registry.json

EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
