import argparse
import hashlib
import json
import shutil
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml


DEFAULT_FEATURES = ["Time"] + [f"V{i}" for i in range(1, 29)] + ["Amount"]
ARTIFACT_SOURCES = {
    "model_pickle": Path("results/logit.pkl"),
    "selected_features_pickle": Path("results/finalvar.pkl"),
    "model_summary": Path("results/model_summary.txt"),
    "balanced_test_report": Path("results/classification_report_ns.txt"),
    "full_dataset_report": Path("results/classification_report_wd.txt"),
    "balanced_test_accuracy": Path("results/accuracy_ns.json"),
    "full_dataset_accuracy": Path("results/accuracy_wd.json"),
}


def main() -> None:
    parser = argparse.ArgumentParser(description="Register a generated model as an immutable version.")
    parser.add_argument("--version", help="Explicit model version id.")
    parser.add_argument("--name", default="Stepwise Logistic Fraud Classifier")
    parser.add_argument("--stage", default="development")
    parser.add_argument("--status", default="candidate")
    parser.add_argument("--threshold", type=float, default=0.5)
    parser.add_argument("--registry", type=Path, default=Path("models/registry.json"))
    parser.add_argument("--versions-dir", type=Path, default=Path("models/versions"))
    parser.add_argument("--copy-artifacts", action="store_true")
    args = parser.parse_args()

    git_commit = _git_value(["rev-parse", "--short", "HEAD"], "unknown")
    branch = _git_value(["rev-parse", "--abbrev-ref", "HEAD"], "unknown")
    created_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    version = args.version or f"fraud-logit-{created_at[:10]}-{git_commit}"
    version_dir = args.versions_dir / version
    version_dir.mkdir(parents=True, exist_ok=True)

    params = _read_yaml(Path("params.yaml"))
    metrics = _collect_metrics()
    features = _collect_features()
    artifacts = _collect_artifacts(version_dir, args.copy_artifacts)

    _write_yaml(version_dir / "params.yaml", params)
    _write_json(version_dir / "metrics.json", metrics)

    manifest = {
        "version": version,
        "created_at": created_at,
        "git_commit": git_commit,
        "source_branch": branch,
        "params_path": str(version_dir / "params.yaml"),
        "metrics_path": str(version_dir / "metrics.json"),
        "artifacts": {artifact["name"]: artifact["path"] for artifact in artifacts},
        "artifact_hashes": {
            artifact["name"]: _sha256(Path(artifact["path"]))
            for artifact in artifacts
            if Path(artifact["path"]).exists()
        },
    }
    _write_json(version_dir / "manifest.json", manifest)

    registry = _read_json(args.registry)
    registry["versions"] = [
        item for item in registry.get("versions", []) if item.get("version") != version
    ]
    registry["versions"].append(
        {
            "version": version,
            "name": args.name,
            "stage": args.stage,
            "status": args.status,
            "algorithm": "statsmodels.Logit",
            "trained_at": created_at,
            "training_data": "creditcard.csv with DVC pipeline",
            "git_commit": git_commit,
            "source_branch": branch,
            "params": params,
            "threshold": args.threshold,
            "features_count": len(features),
            "features": features,
            "metrics": _flatten_metrics(metrics),
            "artifacts": [{"required_for_serving": False, **artifact} for artifact in artifacts],
            "risks": _risks_from_metrics(metrics),
            "notes": "Generated by scripts/register_model.py after a training pipeline run.",
        }
    )
    _write_json(args.registry, registry)
    print(version)


def _collect_artifacts(version_dir: Path, copy_artifacts: bool) -> list[dict[str, Any]]:
    artifacts: list[dict[str, Any]] = [
        {"name": "manifest", "path": str(version_dir / "manifest.json")},
        {"name": "params", "path": str(version_dir / "params.yaml")},
        {"name": "metrics", "path": str(version_dir / "metrics.json")},
    ]

    for name, source in ARTIFACT_SOURCES.items():
        target = version_dir / source.name if copy_artifacts and source.exists() else source
        if copy_artifacts and source.exists():
            shutil.copy2(source, target)
        artifacts.append(
            {
                "name": name,
                "path": str(target),
                "required_for_serving": name in {"model_pickle", "selected_features_pickle"},
            }
        )
    return artifacts


def _collect_metrics() -> dict[str, Any]:
    metrics = {
        "balanced_test": {},
        "full_dataset": {},
    }
    accuracy_ns = _read_json(Path("results/accuracy_ns.json"), default={})
    accuracy_wd = _read_json(Path("results/accuracy_wd.json"), default={})
    metrics["balanced_test"]["accuracy"] = accuracy_ns.get("model_accuracy")
    metrics["full_dataset"]["accuracy"] = accuracy_wd.get("model_accuracy")
    metrics["balanced_test"].update(_parse_classification_report(Path("results/classification_report_ns.txt")))
    metrics["full_dataset"].update(_parse_classification_report(Path("results/classification_report_wd.txt")))
    return metrics


def _parse_classification_report(path: Path) -> dict[str, float]:
    if not path.exists():
        return {}
    for line in path.read_text(encoding="utf-8").splitlines():
        parts = line.split()
        if parts and parts[0] == "1" and len(parts) >= 4:
            return {
                "fraud_precision": float(parts[1]),
                "fraud_recall": float(parts[2]),
                "fraud_f1": float(parts[3]),
            }
    return {}


def _flatten_metrics(metrics: dict[str, Any]) -> list[dict[str, Any]]:
    flattened: list[dict[str, Any]] = []
    for split, split_metrics in metrics.items():
        for name, value in split_metrics.items():
            if value is None:
                continue
            flattened.append(
                {
                    "name": name,
                    "value": value,
                    "split": split,
                    "target_class": "1" if name.startswith("fraud_") else None,
                    "higher_is_better": True,
                }
            )
    return flattened


def _collect_features() -> list[str]:
    try:
        import pickle

        with Path("results/finalvar.pkl").open("rb") as feature_file:
            features = pickle.load(feature_file)
        if isinstance(features, list) and features:
            return [str(feature) for feature in features]
    except Exception:
        pass
    return DEFAULT_FEATURES


def _risks_from_metrics(metrics: dict[str, Any]) -> list[dict[str, str]]:
    risks: list[dict[str, str]] = []
    precision = metrics.get("full_dataset", {}).get("fraud_precision")
    if precision is not None and precision < 0.1:
        risks.append(
            {
                "level": "high",
                "message": f"Fraud precision is {precision:.2f} on the full dataset.",
            }
        )
    return risks


def _git_value(args: list[str], default: str) -> str:
    try:
        return subprocess.check_output(["git", *args], text=True).strip()
    except Exception:
        return default


def _read_yaml(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    with path.open("r", encoding="utf-8") as yaml_file:
        return yaml.safe_load(yaml_file) or {}


def _write_yaml(path: Path, payload: dict[str, Any]) -> None:
    with path.open("w", encoding="utf-8") as yaml_file:
        yaml.safe_dump(payload, yaml_file, sort_keys=False)


def _read_json(path: Path, default: Any = None) -> Any:
    if not path.exists():
        if default is not None:
            return default
        raise FileNotFoundError(path)
    with path.open("r", encoding="utf-8") as json_file:
        return json.load(json_file)


def _write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as json_file:
        json.dump(payload, json_file, indent=2)
        json_file.write("\n")


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as artifact_file:
        for chunk in iter(lambda: artifact_file.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


if __name__ == "__main__":
    main()
